# Generated by Django 4.2 on 2023-05-03 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_link_front', models.TextField(blank=True, null=True)),
                ('image_link_back', models.TextField(blank=True, null=True)),
                ('image_link_right', models.TextField(blank=True, null=True)),
                ('image_link_left', models.TextField(blank=True, null=True)),
                ('image_buy_link', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(verbose_name='Object uploaded by user')),
                ('gender', models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women'), ('Girls', 'Girls')], max_length=10, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('Kids-Girls', 'Kids-Girls'), ('Kids-Unisex', 'Kids-Unisex'), ('Kids-Boys', 'Kids-Boys'), ('Adults-Women', 'Adults-Women'), ('Adults-Unisex', 'Adults-Unisex'), ('Adults-Men', 'Adults-Men')], max_length=25, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=20, null=True)),
                ('usage', models.CharField(blank=True, choices=[('Formal', 'Formal'), ('Smart Casual', 'Smart Casual'), ('Sports', 'Sports'), ('Party', 'Party'), ('Home', 'Home'), ('NA', 'NA'), ('Ethnic', 'Ethnic'), ('Casual', 'Casual'), ('Travel', 'Travel')], max_length=20, null=True)),
                ('main_category', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=60, null=True)),
                ('article_category', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('recall', models.FloatField()),
                ('precision', models.FloatField()),
                ('f1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.imageobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAvatarSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_pfp', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('column_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_item', to='home.imageobject')),
                ('row_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_item', to='home.imageobject')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.imageobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('array_datatype', models.CharField(default='float32', max_length=10)),
                ('image_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.imageobject')),
            ],
        ),
    ]
